# Site settings
title: 独顽且鄙的博客
#SEOTitle: 独顽且鄙的博客
header-img: img/home-bg-o.jpg
email: 18810295909@qq.com
description: "独顽且鄙的博客"
keyword: "JAVA"
url: "http://duwanqiebi.github.io"              # your host, for absolute URL
baseurl: "http://duwanqiebi.github.io"                             # for example, '/blog' if your blog hosted on 'host/blog'


# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

#categories
categories: true
highlighter: rouge

# SNS settings
RSS: false
weibo_username:     duwanqiebi
zhihu_username:     zhang-qiang-26-87
github_username:    duwanqiebi
facebook_username:  duwanqiebi

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

paginate: 10

# Duoshuo settings
duoshuo_username: duwanqiebi
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false 


highlighter: rouge
permalink: pretty
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
#anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM 
  
  
 # Friends
friends: [
    {
        title: "Zark's Blog",
        href: "http://zark.space/"
    }
]
